# Generated by Django 4.1.7 on 2023-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_to_do_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="isDone",
            field=models.BooleanField(default=False),
        ),
    ]
